# Generated by Django 2.2.3 on 2019-07-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='quotes',
            field=models.ManyToManyField(to='core.Quote'),
        ),
    ]
