# Generated by Django 2.2.3 on 2019-07-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='final',
            field=models.TextField(verbose_name='Final Diagnostic'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='initial',
            field=models.TextField(verbose_name='Initial Diagnostic'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='reception_datetime',
            field=models.DateTimeField(help_text='YYYY/mm/dd HH:MM'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='repairs',
            field=models.TextField(verbose_name='Repairs'),
        ),
    ]
