# Generated by Django 2.2.3 on 2019-08-01 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190722_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='service',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='client',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Car'),
        ),
        migrations.AddField(
            model_name='quote',
            name='diagnostic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Diagnostic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Quote'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
