# Generated by Django 2.2.3 on 2019-07-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190719_2154'),
        ('core', '0002_auto_20190722_2209'),
    ]

    operations = [
    ]
