# Generated by Django 2.2.3 on 2019-08-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190801_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('c', 'Completed'), ('p', 'Paid')], default='o', max_length=10),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('o', 'Open'), ('a', 'Accepted')], default='o', max_length=10),
        ),
    ]
