# Generated by Django 2.2.4 on 2019-08-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190801_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='release',
            name='quotes',
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='item',
            name='quote',
        ),
        migrations.AddField(
            model_name='item',
            name='diagnostic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Diagnostic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='reception_datetime',
            field=models.DateTimeField(help_text='YYYY-mm-dd HH:MM:SS'),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.DeleteModel(
            name='Release',
        ),
    ]
