# Generated by Django 2.2.3 on 2019-07-13 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190710_0452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('client', 'brand', 'model', 'year')},
        ),
    ]
