# Generated by Django 2.2.4 on 2019-08-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190801_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostic',
            options={'ordering': ('-reception_datetime', 'status')},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
