# Generated by Django 2.2.3 on 2019-07-17 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190713_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Car'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Client'),
        ),
    ]
