# Generated by Django 2.2.3 on 2019-07-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190717_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='client',
        ),
    ]
