# Generated by Django 2.2.4 on 2019-08-09 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20190727_1742'),
        ('core', '0007_auto_20190806_2231'),
    ]

    operations = [
    ]
