# Generated by Django 2.1.7 on 2019-12-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190815_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='final',
            field=models.TextField(blank=True, null=True, verbose_name='Final Diagnostic'),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='repairs',
            field=models.TextField(blank=True, null=True, verbose_name='Repairs'),
        ),
    ]
