# Generated by Django 2.1.7 on 2020-01-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191203_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='address',
            field=models.TextField(default='', help_text='Address'),
            preserve_default=False,
        ),
    ]
